---
- hosts: all
  become: true
  connection: local
  roles:
  - motd

  tasks:
#    - name: Yum update
#      yum: name=* state=latest
#      register: updates

    - name: Debug registered updates
      debug:
       var: updates

    - name: Installing Open VMware Tools (open-vm-tools) for CentOS/RHEL 7 and higher.
      yum: name=open-vm-tools state=installed
      when: ansible_distribution_major_version|int >= 7

    - name: Start vmtoolsd and enable vmtoolsd to start during boot for CentOS/RHEL 7 and higher.
      service: name=vmtoolsd state=started enabled=yes
      failed_when: false
      when: ansible_distribution_major_version|int >= 7
